### ISSUE TITLE
Needs a mobile first responsive navbar design

### ISSUE THREAD

**Issue by ScorchingShade** [ScorchingShade/Pinch#1]
create a navbar with suitable themes for mobile first design

**Comment by amycruz97** [comment]
I will work on this for hacktoberfest. but what exactly do you want to achieve

**Comment by ShashankRawatgit92** [comment]
i have experience sir pls assign me

**Comment by ScorchingShade** [comment]
Please clone the repo and then you will see two navbar types from css. Your goal is to generate a webkit for Different screen sizes where the navbar is optimised for mobile use.

Generate a pull request and if everything goes well i will merge the issue

**Comment by Abhishekchauhan089** [comment]
@ScorchingShade I would like to work on this issue

**Comment by ScorchingShade** [comment]
Sure @Abhishekchauhan089 please do so and raise a PR

**Comment by ScorchingShade** [comment]
I have done this, not required any work now
